"""Email delivery service for legal notices via AWS SES.

Sends the PDF notice via email to either:
- The complainant (self-send tier, ₹199) — user gets PDF to forward/print/send
- The company + complainant copy (lawyer tier, ₹599) — sent from advocate's
  verified email address with read-receipt request

In production, wired to AWS SES for deliverability.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from email.message import EmailMessage
from email.utils import formataddr

import re

import boto3
from botocore.exceptions import ClientError

_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


@dataclass
class DeliveryResult:
    success: bool
    message: str
    recipients: list[str]
    message_id: str | None = None


def send_notice_email(
    *,
    to_email: str,
    to_name: str,
    cc_emails: list[str] | None = None,
    subject: str,
    body_text: str,
    pdf_bytes: bytes,
    pdf_filename: str = "Legal_Notice.pdf",
    request_read_receipt: bool = False,
) -> DeliveryResult:
    """Send a legal notice PDF as an email attachment via AWS SES."""
    from_email = os.getenv("NOTICE_FROM_EMAIL", "support@lawly.store")
    from_name = os.getenv("NOTICE_FROM_NAME", "Lawly")
    aws_region = os.getenv("AWS_REGION", "ap-south-1")

    if not from_email:
        return DeliveryResult(
            success=False,
            message="Email not configured. Set NOTICE_FROM_EMAIL in .env",
            recipients=[to_email],
        )

    msg = EmailMessage()
    msg["From"] = formataddr((from_name, from_email))
    msg["To"] = formataddr((to_name, to_email))
    msg["Subject"] = subject

    if cc_emails:
        safe_cc = [e for e in cc_emails if _EMAIL_RE.match(e) and "\n" not in e and "\r" not in e]
        if safe_cc:
            msg["Cc"] = ", ".join(safe_cc)

    if request_read_receipt:
        msg["Disposition-Notification-To"] = from_email
        msg["X-Confirm-Reading-To"] = from_email

    msg.set_content(body_text)
    if pdf_bytes and pdf_filename:
        msg.add_attachment(
            pdf_bytes,
            maintype="application",
            subtype="pdf",
            filename=pdf_filename,
        )

    all_recipients = [to_email] + (safe_cc if cc_emails else [])

    try:
        ses_client = boto3.client("ses", region_name=aws_region)
        response = ses_client.send_raw_email(
            Source=from_email,
            Destinations=all_recipients,
            RawMessage={"Data": msg.as_bytes()},
        )
        return DeliveryResult(
            success=True,
            message=f"Notice delivered to {', '.join(all_recipients)}",
            recipients=all_recipients,
            message_id=response.get("MessageId"),
        )
    except ClientError as e:
        error_msg = e.response["Error"]["Message"]
        print(f"AWS SES Delivery failed: {error_msg}")
        return DeliveryResult(
            success=False,
            message=f"AWS SES error: {error_msg}",
            recipients=all_recipients,
        )
    except Exception as e:
        print(f"Failed to send email: {str(e)}")
        return DeliveryResult(
            success=False,
            message=f"Delivery failed: {str(e)}",
            recipients=all_recipients,
        )


def build_self_send_body(complainant_name: str, company_name: str) -> str:
    """Build email body for self-send (₹199) tier."""
    return (
        f"Dear {complainant_name},\n\n"
        f"Your legal notice regarding {company_name} is attached as a PDF.\n\n"
        f"Next steps:\n"
        f"1. Review the notice carefully and fill in any [placeholder] fields\n"
        f"2. Forward the attached PDF to the company's official grievance email\n"
        f"   with 'read receipt' / 'delivery receipt' enabled as proof of service\n"
        f"3. Also CC the notice to any regulatory stakeholders listed in the\n"
        f"   escalation strategy section of the notice\n"
        f"4. Save all sent-email confirmations and read receipts for your records\n"
        f"5. If no response within the cure period stated in the notice, you may file a\n"
        f"   consumer complaint via e-daakhil.nic.in\n\n"
        f"This notice was generated by an AI system. For legal review, consider "
        f"upgrading to the Lawyer-Assisted tier.\n\n"
        f"Regards,\n"
        f"Lawly"
    )

def build_lawyer_send_body(complainant_name: str, company_name: str, company_email: str) -> str:
    return (
        f"Dear Sir/Madam,\n\n"
        f"Under instructions from my client, {complainant_name}, I am serving upon you "
        f"the enclosed Legal Notice regarding your deficient service/product.\n\n"
        f"Please find the Legal Notice annexed hereto as a PDF attachment.\n\n"
        f"You are required to comply with the demands set forth therein within the cure "
        f"period specified in the notice, failing which my client shall be constrained to "
        f"initiate appropriate proceedings before the competent Consumer Disputes Redressal "
        f"Commission, at your risk, cost, and consequences.\n\n"
        f"This email constitutes valid electronic service of notice.\n\n"
        f"Kindly acknowledge receipt of this notice.\n\n"
        f"Yours faithfully,\n"
        f"[Advocate Name]\n"
        f"[Enrollment No.]\n"
        f"On behalf of: {complainant_name}"
    )
